name: Build and Push Docker Image

on:
  push:
    branches: [master, develop]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Determine Docker image tag
        id: vars
        run: |
          if [[ "${GITHUB_REF_NAME}" == "develop"]]; then
            echo "tag=${{ secrets.DOCKERHUB_USERNAME }}/aiogram-shop-bot-develop:latest" >> $GITHUB_ENV
          else
            echo "tag=${{ secrets.DOCKERHUB_USERNAME }}/aiogram-shop-bot:latest" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.tag }}

      - name: Clean all
        run: rm -rf ./*
